# Generated by mc: 9:31 3.18.2019.
#
	.data
	.text
main:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -24		# allocate locals
	li	$v0, 0
	sw	$v0, -16($fp)
	li	$v0, 1
	sw	$v0, -8($fp)
	lw	$t1, -8($fp)
	addi	$sp, $sp, -4		# push 
	sw	$t1, 0($sp)
	addi	$sp, $sp, -4		# push 
	sw	$ra, 0($sp)
	jal	f
	lw	$ra, 0($sp)		# pop ra
	addi	$sp, $sp, 4
	addi	$sp, $sp, 4		# deallocate args
	sw	$v0, -12($fp)
	lw	$v0, -12($fp)
	sw	$v0, -16($fp)
	lw	$v0, -16($fp)
	sw	$v0, -20($fp)
	lw	$a0, -20($fp)
	li	$v0, 1			# $v0 gets print_int code for syscall
	syscall				# print
	li	$v0, 0
	sw	$v0, -24($fp)
	lw	$a0, -24($fp)
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	li	$v0, 17			# $v0 gets exit code for syscall
	syscall				# Exit here
f:	addi	$sp, $sp, -4		# push fp
	sw	$fp, 0($sp)
	move	$fp, $sp		# fp <- sp
	addi	$sp, $sp, -68		# allocate locals
	li	$v0, 0
	sw	$v0, -52($fp)
	li	$v0, 0
	sw	$v0, -64($fp)
	li	$v0, 1
	sw	$v0, -52($fp)
	li	$v0, 0
	sw	$v0, -64($fp)
l0:	nop
	li	$v0, 100
	sw	$v0, -20($fp)
	lw	$t1, -64($fp)
	lw	$t2, -20($fp)
	slt	$v0, $t1, $t2
	sw	$v0, -24($fp)
	lw	$v0, -24($fp)
	beqz	$v0, l1
	li	$v0, 20
	sw	$v0, -28($fp)
	lw	$t1, -52($fp)
	lw	$t2, -28($fp)
	slt	$v0, $t1, $t2
	sw	$v0, -32($fp)
	lw	$v0, -32($fp)
	beqz	$v0, l2
	lw	$v0, 8($fp)
	sw	$v0, -52($fp)
	li	$v0, 1
	sw	$v0, -40($fp)
	lw	$t1, -64($fp)
	lw	$t2, -40($fp)
	add	$v0, $t1, $t2
	sw	$v0, -44($fp)
	lw	$v0, -44($fp)
	sw	$v0, -64($fp)
	j	l3
l2:	nop
	lw	$v0, -64($fp)
	sw	$v0, -52($fp)
	li	$v0, 2
	sw	$v0, -56($fp)
	lw	$t1, -64($fp)
	lw	$t2, -56($fp)
	add	$v0, $t1, $t2
	sw	$v0, -60($fp)
	lw	$v0, -60($fp)
	sw	$v0, -64($fp)
l3:	nop
	j	l0
l1:	nop
	lw	$v0, -52($fp)
	sw	$v0, -68($fp)
	lw	$v0, -68($fp)
	move	$sp, $fp
	lw	$fp, 0($sp)		# pop restore fp
	addi	$sp, $sp, 4
	jr	$ra				# return
